controller_joint_names: ['', 'RF_HAA', 'RF_HFE', 'RF_KFE', 'RM_HAA', 'RM_HFE', 'RM_KFE', 'RB_HAA', 'RB_HFE', 'RB_KFE', 'LF_HAA', 'LF_HFE', 'LF_KFE', 'LM_HAA', 'LM_HFE', 'LM_KFE', 'LB_HAA', 'LB_HFE', 'LB_KFE', ]
